name: check-secret

on:
  workflow_call:
    secrets:
      secret:
        required: true
    outputs:
      set:
        value: ${{ jobs.check-secret.outputs.set }}

jobs:
  check-secret:
    runs-on: ubuntu-22.04
    outputs:
      set: ${{ steps.check-secret.outputs.set }}
    steps:
      - name: Check if secret is set
        id: check-secret
        run: |
          if [ "${{ secrets.secret }}" != "" ]; then
            echo "set=true" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Show result
        run: |
          echo "set: ${{ steps.check-secret.outputs.set }}"
        shell: bash
